server:
  port: 8089

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**
#    config:
#      uri: http://config-service:8888
#      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud: DEBUG
