server:
  port: 8082  # Уникальный порт для company-service

spring:
  application:
    name: company-service  # Имя сервиса для Eureka
  datasource:
    url: jdbc:postgresql://localhost:5433/company_db  # Подключение к своей БД
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20           # Увеличьте размер пула
  #      connection-timeout: 30000       # Таймаут подключения (ms)
  #      leak-detection-threshold: 60000 # Обнаружение "утечек"
  #      idle-timeout: 600000            # Макс время бездействия
  #      max-lifetime: 1800000           # Макс время жизни соединения
  #  cloud:
  #    config:
  #      uri: http://config-service:8888
  #      fail-fast: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        session.events.log: true
        generate_statistics: true
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Регистрация в Eureka

user:
  service:
    url: http://localhost:8081
#    url: http://host.docker.internal:8081 # Для локального тестирования

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud: DEBUG
    ru.nikrink.company-service: DEBUG
    feign: DEBUG
