server:
  port: 8081  # Уникальный порт для user-service

spring:
  application:
    name: user-service  # Имя сервиса для Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db  # Подключение к своей БД
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  cloud:
#    loadbalancer:
#      cache:
#        enabled: false
#    config:
#      uri: http://config-service:8888
#      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# для проверки
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: basic
      company-service: # Можно указать для конкретного сервиса
        connectTimeout: 10000
        readTimeout: 60000

company:
  service:
    url: http://localhost:8082
#    url: http://company-service:8082

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud: DEBUG
    ru.nikrink.user-service: DEBUG  # Ваш пакет (если нужно)
    feign: DEBUG
    org.springframework.web: DEBUG
